selection:
  max_tweets_per_run: 5
  min_engagement_threshold: 10
  max_tweet_age_hours: 4
  exclude_retweets: true
  exclude_replies: true
  blacklisted_users: []
  blacklisted_keywords: 
    - "crypto"
    - "nft"
    - "investment advice"

reply:
  base_prompt: "write an impactful reply to the following so that it teaches something new and contrary to the status-quo views: {tweet_content}"
  max_reply_length: 280
  temperature: 0.7
  model: "llama-3.1-sonar-small-128k-online"

app:
  log_level: "INFO"
  dry_run: false
  data_dir: "data"
  log_dir: "logs"

rate_limits:
  twitter_read_per_15min: 240  # Conservative limit (80% of 300)
  twitter_write_per_15min: 240  # Conservative limit (80% of 300)
  perplexity_per_hour: 480     # Conservative limit (80% of 600)
